### ISSUE TITLE
Grails wrapper doesn't work due to missing gradle.properties

### ISSUE THREAD

**Issue by rlovtangen** [grails-guides/react-combined#3]
server/grailsw fails to run due to missing gradle.properties:

```
/server$ ./grailsw create-controller Foo
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Could not determine grails wrapper version due to missing gradle.properties file. Using existing jar
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at grails.init.Start.main(Start.java:127)
Caused by: java.lang.RuntimeException: Could not determine grails version due to missing properties file
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at grails.init.RunCommand.main(RunCommand.groovy:22)
	... 5 more
```

The guide says:

> We did one minor change. We moved the initial/server/gradle.properties to the root directory initial/gradle.properties

Why is that? The only properties in the file is `grailsVersion` and `gormVersion`. Is that needed at root? If I move it back to `server`, the Grails wrapper works fine, and I am still able to run the project with `./gradlew bootrun --parallel` and build with `./gradlew assembleServerAndClient` and run jar.

**Comment by niravassar** [comment]
you are correct. This is a false statement and i took it out
